### ISSUE TITLE
Disable button download and print

### ISSUE THREAD

**Issue by fiq265** [goodnesskay/LARAVEL-PDF-VIEWER#2]
How to disable button download and print in this viewer?

**Comment by goodnesskay** [comment]
Hello, were you able to install the package successfully?

**Comment by fiq265** [comment]
@goodnesskay yes, Im successfully install the package on laravel 5.4

**Comment by goodnesskay** [comment]
While installing, did you follow the documentation?

**Comment by fiq265** [comment]
Yes, I follow exactly. I can use it well. I just want during display the pdf, function like download and print disable or hide so other user cant get the pdf file, only read from there

**Comment by goodnesskay** [comment]
okay. For now, the feature you have requested is not yet available but in the next release, it will be released.

**Comment by fiq265** [comment]
That is awesome. Thanks
